# Generated by Django 4.2.7 on 2025-10-04 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model_type', models.CharField(choices=[('random-forest', 'Random Forest'), ('linear-regression', 'Linear Regression'), ('neural-network', 'Neural Network'), ('svm', 'Support Vector Machine'), ('gradient-boosting', 'Gradient Boosting')], max_length=20)),
                ('analysis_type', models.CharField(choices=[('own-data', 'Own Data'), ('app-data', 'App Data')], max_length=10)),
                ('hyperparameters', models.JSONField()),
                ('accuracy', models.FloatField()),
                ('precision', models.FloatField()),
                ('recall', models.FloatField()),
                ('f1_score', models.FloatField()),
                ('mae', models.FloatField()),
                ('r2_score', models.FloatField()),
                ('training_time', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_file', models.FileField(blank=True, null=True, upload_to='models/')),
                ('target_variable', models.CharField(blank=True, max_length=100, null=True)),
                ('input_variables', models.JSONField(blank=True, null=True)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('dataset_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.JSONField()),
                ('prediction_result', models.JSONField()),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='ml_models.trainedmodel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
